# Build settings
plugins:
  - jemoji
  - jekyll-paginate
  - jekyll-archives

# Site settings
title: "Cristian Cardellino"
description: > # this means to ignore newlines until "email:"
    Notes of a Computer Scientist

email: ccardellino@unc.edu.ar

# blog logo
logo: "/assets/img/logo.png"
float_logo: true

# blog cover
cover: "/assets/img/cover.jpg"

name: 'Cristian Cardellino'
author: 'Cristian Cardellino'
author_image: "/assets/img/me.jpg"

paginate: 5

url: "https://crscardellino.github.io" # the base hostname & protocol for your site
baseurl: ""

# used to display twitter cards
twitter_handle: '@crscardellino'

google_analytics: UA-30086759-1

social:
  - icon: twitter
    url: https://twitter.com/crscardellino
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="
  - icon: mastodon
    url: https://mastodon.social/@crscardellino
    desc: Follow me on mastodon
    share_url: https://mastodon.social/share
    share_title: ?text=
    share_link: "&amp;url="
  - icon: github
    url: https://github.com/crscardellino
    desc: Fork me on github
    share_url:
    share_title:
    share_link:

excerpt_separator: <!-- more -->

include:
  - _pages

jekyll-archives:
  enabled:
    - year
    - month
    - tags
  layouts:
    year: year-archive
    month: month-archive
    tag: tag-archive
  permalinks:
    year: 'archive/:year/'
    month: 'archive/:year/:month/'
    tag: 'archive/tag/:name/'
