# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Cristian Cardellino"
description: > # this means to ignore newlines until "email:"
    Notes of a Computer Scientist

email: ccardellino@unc.edu.ar

# blog logo
logo: "/assets/images/me.jpg"
float_logo: true 

# blog cover
cover: "/assets/images/cover.jpg"

name: 'Cristian Cardellino'
author: 'Cristian Cardellino'
author_image: "/assets/images/me.jpg"

paginate: 5

url: "http://crscardellino.me" # the base hostname & protocol for your site
baseurl: ""

# used to display twitter cards
twitter_handle: '@neurotikal'

# google_analytics: UA-XXXXX-X

social:
  - icon: twitter
    url: https://twitter.com/neurotikal
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon: github
    url: https://github.com/crscardellino
    desc: Fork me on github
    share_url:
    share_title:
    share_link:

excerpt_separator: <!-- more -->

jekyll-archives:
  enabled: 
    - year
    - month
    - tags
  layouts: 
    year: year-archive
    month: month-archive
    tag: tag-archive
  permalinks:
    year: 'archive/:year/'
    month: 'archive/:year/:month/'
    tag: 'archive/tag/:name/'
